# Generated by Django 5.1.1 on 2024-09-12 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('poster', models.ImageField(blank=True, upload_to='EventPoster/')),
                ('venue', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('ksh', models.PositiveIntegerField(blank=True)),
                ('updated', models.TimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attendees', models.ManyToManyField(blank=True, default=None, related_name='attendees', to='profiles.profile')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='profiles.profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
